### ISSUE TITLE
Cannot connect accounts in web3.js v1.0.0

### ISSUE THREAD

**Issue by Arulkp** [aionnetwork/aion_web3#12]
I try to connect privatenet using web3.min.js (web3@1.0.0 version). It can't connect with accounts but when using web3@0.20.0 version connect successfully.i want execute send sign transaction and generate privatekey using web3..how do this

**Comment by tcrowe** [comment]
Until someone else answers specifically I can refer you to some projects I am also digging through to find answers:

+ aion wallet site https://testwallet.aion.network/
  * open console
  * `web3`
+ a similar deployment https://wallet.aionpool.online/
  * open console
  * `web3`
+ source https://github.com/aionnetwork/aion_wallet

The best we can do now is go through the source until the next version is available and documented. #10

**Comment by collabcoindev** [comment]
I can't access any of those wallets above, it is either CORS or nodes are down, I am unsure. 
Tried mainnet, conquest and local node.

**Comment by tcrowe** [comment]
You can try again now:

```
npm install aionnetwork/aion_web3#v1.0
```

Create accounts:
https://gist.github.com/tcrowe/943e4f082abfe2133cd9a15f220e5fc3

Compile solidity:
https://gist.github.com/tcrowe/07c64aa6fe29bd3c7b8157e2c731ac5e

Sign and raw transaction:
https://gist.github.com/tcrowe/b47a63e5d815b394ce49df810be7b9cf

Recommending to close out this issue

Also join the chat @Arulkp @collabcoindev 👍🏼 https://gitter.im/aionnetwork/Lobby

**Comment by erik-iglikov** [comment]
This issue requires more detailed name

**Comment by aion-kelvin** [comment]
Haven't heard back in a while on this one so I'm going to close it.

Aion Web3 v1.1.0 was recently released; if you are still having issues please try this guide https://learn.aion.network/v1.0/docs/deploy-a-smart-contract-using-web3.  If there's further issues feel free to open a new issue.
