### ISSUE TITLE
Need documentation on how to use the release

### ISSUE THREAD

**Issue by iamyulong** [aionnetwork/aion_web3#14]
The `aion-web3` npm package is outdated. Need instruction, or an updated README, on how to use the release with nodejs, from another project.

**Comment by tcrowe** [comment]
Hey @yulongaion :wave:

You can now install aion-web3 via github branch until it's published.

```
npm install aionnetwork/aion_web3#v1.0
```

Ethereum web3 docs for how to use it: https://web3js.readthedocs.io/en/1.0/

---

## Aion Web3 examples

Create accounts:
https://gist.github.com/tcrowe/943e4f082abfe2133cd9a15f220e5fc3

Compile solidity:
https://gist.github.com/tcrowe/07c64aa6fe29bd3c7b8157e2c731ac5e

Sign and raw transaction:
https://gist.github.com/tcrowe/b47a63e5d815b394ce49df810be7b9cf

---

Join us in the chat 🤓  https://gitter.im/aionnetwork/Lobby

**Comment by erik-iglikov** [comment]
@mohnjatthews can you take a look at these `Aion Web3 examples` and estimate if we want to add those somewhere in our docs?

**Comment by johnnymatthews** [comment]
> @mohnjatthews can you take a look at these `Aion Web3 examples` and estimate if we want to add those somewhere in our docs?

Will do 👍

**Comment by qoire** [comment]
https://web3js.readthedocs.io/en/1.0/, can we modify this to fit our needs?

**Comment by aion-kelvin** [comment]
From https://github.com/aionnetwork/aion_web3/issues/32:

>  I recommend to change the https://github.com/aionnetwork/aion_web3/blob/v1.0/docs/web3-eth.rst#sendsignedtransaction by using aion-keystore instead of ethereumjs-tx

- Need to update https://github.com/aionnetwork/aion_web3/blob/v1.0/docs/web3-eth.rst#sendsignedtransaction
- Actually, as part of v1.0.1 release, we want all aion-keystore functionality to be inside aion-web3.  So, the documentation should reflect that -- but it definitely shuoldn't reference ethereumjs-tx

**Comment by aion-kelvin** [comment]
https://docs.aion.network/docs/ 
https://learn.aion.network/v1.0/docs/deploy-a-smart-contract-using-web3
