### ISSUE TITLE
Update utils, etc to use Aion terminology

### ISSUE THREAD

**Issue by aion-kelvin** [aionnetwork/aion_web3#16]
Since forking from eth web3, there's a bunch of code that still references Eth-specific terminology for cryptocurrency quantities; i.e. wei.  Need to update to use Aion terminology: https://github.com/aionnetwork/aion/wiki/Aion-Terminology

**Comment by tcrowe** [comment]
The trade off is that people converting their app will need to change it. If you decide to change the terms anyway you can add to a "Converting from Ethereum Web3" document.

**Comment by johnnymatthews** [comment]
> add to a "Converting from Ethereum Web3" document.

Agreed. I'll make a start on that stuff.

**Comment by aion-kelvin** [comment]
fixed by https://github.com/aionnetwork/aion_web3/pull/19
