### ISSUE TITLE
./index.js might be from the old version

### ISSUE THREAD

**Issue by tcrowe** [aionnetwork/aion_web3#20]
Branch: v1.0

https://github.com/aionnetwork/aion_web3/blob/v1.0/index.js

This file doesn't work and might be an artifact from the old version.

Recommendation: `git rm ./index.js`

**Comment by aion-kelvin** [comment]
It is being used by the `browserify` npm script (in packages.json).  However looking at the actual file, it seems to refer to a file that doesn't even exist.  I'll look into it.

**Comment by aion-kelvin** [comment]
The file is used by `browserify` npm script.  However it had a bug in it.  PR for the fix https://github.com/aionnetwork/aion_web3/pull/52
