### ISSUE TITLE
Question about sign the transaction and send transaction

### ISSUE THREAD

**Issue by zzq229** [aionnetwork/aion_web3#32]
I have been using aion-keystore ( https://www.npmjs.com/package/aion-keystore ) to sign transaction and web3.eth.sendSignedTransaction ( https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendsignedtransaction ) to send raw transaction but I got error. Wonder if there is any example about a transaction object in Aion or there is any differences between Aion and Ethereum in sendSignedTransaction function?

**Comment by erik-iglikov** [comment]
Hey @zzq229 what error did you get when you were trying to send a transaction?
Here's the documentation we have for transacting with web3 https://github.com/aionnetwork/aion_web3/blob/v1.0/docs/web3-eth.rst#sendsignedtransaction

**Comment by zzq229** [comment]
I am using aion-keystore ( https://www.npmjs.com/package/aion-keystore ) to sign the transaction, and web3.eth.sendSignedTransaction ( https://github.com/aionnetwork/aion_web3/blob/v1.0/docs/web3-eth.rst#sendsignedtransaction ) to send raw transaction. The signature works fine but the Aion node is getting "`ERROR API  [XNIO-1 task-2]: <get-transaction-receipt msg=tx-info-null>"` error

**Comment by zzq229** [comment]
I have solved it individually, the error message in Aion node could be ignore and it takes a bit longer than Ethereum. I recommend to change the https://github.com/aionnetwork/aion_web3/blob/v1.0/docs/web3-eth.rst#sendsignedtransaction by using aion-keystore instead of ethereumjs-tx

**Comment by erik-iglikov** [comment]
Thanks for suggestion @zzq229.
@aion-kelvin can you take a look at that?

**Comment by aion-kelvin** [comment]
Hey @zzq229 thanks for the report!  Glad you eventually got it to work.

You mentioned:

>web3.eth.sendSignedTransaction ( https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendsignedtransaction ) to send raw transaction but I got error.

If you could provide the JS code you used and the error you received, that would be very helpful.

As for updating the Github docs, we have an issue open for addressing the documentation for web3.  I've included your suggestion in that issue and we'll track it there.

**Comment by aion-kelvin** [comment]
Since I haven't heard back with extra details about the info, I'm going to close this issue.  If there's more info/problems feel free to open a new issue.

The documentation update will be tracked in https://github.com/aionnetwork/aion_web3/issues/14.  Here is a code example of how to sign and send transaction in case you're still having problems:

```
const privateKey = '0xPkHere'
const recipientAddr = '0xRecipientAddrHere';

const Web3 = require('aion-web3-v1.0'); // in the future, will become 'aion-web3' 
const web3 = new Web3(new Web3.providers.HttpProvider("http://127.0.0.1:8545"));

const account = web3.eth.accounts.privateKeyToAccount(privateKey)

transactionPayload = { 
  to: recipientAddr,
  value: 1,
  gas: 21000, 
}

account.signTransaction(transactionPayload, (err, res) => {
    if (err) {
        console.log(err)
        return;
    }
    web3.eth.sendSignedTransaction(res.rawTransaction).on('receipt', (r) => { 
        console.log('txHash =', r.transactionHash)
    })
})
```
