### ISSUE TITLE
NPM Package update

### ISSUE THREAD

**Issue by luyzdeleon** [aionnetwork/aion_web3#33]
Hello,

When will version 1.0.0 of the NPM package will be uploaded? Version 0.0.3 was the latest published.

**Comment by aion-kelvin** [comment]
For the moment, v1.0 can be accessed from this npm package: https://www.npmjs.com/package/aion-web3-v1.0 

At the moment it is still prone to some last-minute changes.  By the end of Nov there will be an official announcement and release.  Stay tuned for details.
