### ISSUE TITLE
Feature parity with aion-keystore package

### ISSUE THREAD

**Issue by aion-kelvin** [aionnetwork/aion_web3#39]
aion_web3 should subsume aion-keystore.  Once all features implemented, remove aion-keystore.

**Comment by qoire** [comment]
``aion-keystore`` has implemented #23, need to integrate, and we can close both tickets

**Comment by aion-kelvin** [comment]
@qoire Do you have some example code of how to use aion-keystore to do #23 (sign arbitrary message)?  In its readme I see examples for how to sign a transaction, but I'm not sure if that's something different from 'arbitrary message.'

**Comment by aion-kelvin** [comment]
blocked on pr https://github.com/aionnetwork/aion_web3/pull/50

**Comment by qoire** [comment]
https://github.com/aionnetwork/aion_web3/commit/1cc70d25bc158e2f725896a8bc33d73234416df0
