### ISSUE TITLE
Modify web3 bundle to include node environment

### ISSUE THREAD

**Issue by nuco-chris** [aionnetwork/aion_web3#4]
As indicated by some users, the ``aion_web3`` package currently looks for legacy nodejs environments.

## References
https://forum.aion.network/t/web3api-setup-node-nodejs/152

**Comment by 4math2379** [comment]
Nice tanks for the informations

**Comment by aion-kelvin** [comment]
I believe this is resolved in the version 1.0 and above.  I don't have nodejs-legacy and it works fine for me.  Feel free to make another issue if this is still a problem.
