### ISSUE TITLE
Verify that transaction errors from kernel are surfaced in web3

### ISSUE THREAD

**Issue by aion-kelvin** [aionnetwork/aion_web3#43]
The kernel recently improved its error reporting; an error code is now given when a transaction fails, and the error code gives some info about why it failed.  Need to make sure that failed transactions invoked from Web3 receives this error and surfaces it to the user. 

If it is not currently working, then as part of this issue, implement and test this functionality.

**Comment by arajasek** [comment]
Looked into this, needed a small change (found in PR #49), following which the behaviour is correct.
