### ISSUE TITLE
Not able to fetch pending transactions of a specific address with `eth.getTransactionCount`

### ISSUE THREAD

**Issue by erik-iglikov** [aionnetwork/aion_web3#46]
**Web3 version**: 1.0.0 (latest clone, info from package.json)

**Command(s) triggering the issue**:
1. `eth.getTransactionCount("0xa0661d1ec255e885c6a2de292df7d6da98a96ce1071851238c79ba04d20204bf", "pending")`
Expected behavior: should give me the amount of pending txs
Actual behavior: gets stuck and gives `Error: Returned error: Execution error`

2. `eth.getTransactionCount("0xa0661d1ec255e885c6a2de292df7d6da98a96ce1071851238c79ba04d20204bf")`
Expected behavior: should the number that represents the amount of transactions(including pending ones) for this specific address
Actual behavior: only gives the amount of completed transactions 

Kernel issue that blocks this one: https://github.com/aionnetwork/aion/issues/695

**Comment by arajasek** [comment]
The kernel issue has been fixed, this can be closed upon the next release of the kernel.
