### ISSUE TITLE
NPM issues

### ISSUE THREAD

**Issue by pfuhrmann** [aionnetwork/aion_web3#5]
Hi, there are few issues with the NPM packages. ~But more importantly, why you do not include `package-lock.json` file to have stable dependencies between developers?~ Disregard this as I was referring to the packaged version in the tar file. Also, I would recommend using Yarn which is faster and handles dependencies better.

`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue  
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 576 packages in 16.218s  
`

**Comment by apalissery** [comment]
We are looking into it.

**Comment by collabcoindev** [comment]
Any news on this?

**Comment by erik-iglikov** [comment]
@collabcoindev sorry for a delayed response.
Can you confirm that you getting this error with the newest version of our web3 1.0+ ?

**Comment by aion-kelvin** [comment]
I don't believe that this is an issue anymore with v1.0+ as I did `npm install aion-web3-v1.0` and it didn't find any vulnerabilities.  Our dependencies are a little messed up right now and I'm fixing them; will keep an eye out to see if there's any other vulnerabilities/deprecated stuff and fix if needed.

**Comment by aion-kelvin** [comment]
In the branch v1.0, the two packages mentioned in the original post are of the recommended version (or higher). 

```
sergiu@aion-XPS-8930:~/repos/aion_web3$ npm view graceful-fs version
4.1.11
sergiu@aion-XPS-8930:~/repos/aion_web3$ npm view minimatch version                                       
3.0.4
```

So, I'm going to close this.  If there's another specific issue, please feel free to cut a new issue.
