### ISSUE TITLE
Requesting keystore import export functions

### ISSUE THREAD

**Issue by ghost** [aionnetwork/aion_web3#57]
## Bug Report Template

Please include the following information when reporting an issue you are facing while using the Aion Web3 API.

**Web3 version**: 1.1.0

**Command(s) triggering the issue**: Requesting more features

**API output**: N/A

This is a feature request
**Feature Request** : Requesting two functions to be added to aion-web3-eth-accounts

* decryptFromRlp : Help decrypt keystore file providing password
* encryptToRlp : Help encrypt current account with a password

This is a feature parity request compare to aion-keystore.

**Comment by aion-kelvin** [comment]
Hi @kushptlapigarage,

Do either of these fit your needs?

- web3.eth.encrypt / decrypt
  - https://docs.aion.network/docs/web3-eth-accounts#section-encrypt
  - https://docs.aion.network/docs/web3-eth-accounts#section-decrypt
- web3.eth.wallet.encrypt / decrypt:
  - https://docs.aion.network/docs/web3-eth-accounts#section-wallet-encrypt
  - https://docs.aion.network/docs/web3-eth-accounts#section-wallet-decrypt

**Comment by ghost** [comment]
These were the functions I was looking for. Thank You!
