### ISSUE TITLE
Sending a signed transaction when deoploying a contract does not return the transaction receipt.

### ISSUE THREAD

**Issue by hamzahayat** [aionnetwork/aion_web3#58]
**Description:**  While deploying a contract by grabbing the contract's `encodedABI` and passing it through as the `data` field in the `signTransaction` method, and then sending the signed transaction through `sendSignedTransaction(signedTransaction.rawTransaction)` an error is thrown (Error shown below).

**Code Snippet:**

```
  const contract = new web3.eth.Contract(contractAbi);

  const deployableContract = await contract.deploy({
    data: contractCode,
    arguments: ['Token Name', 'TKN', 1, 40000]
  });

  const contractData = deployableContract.encodeABI();
  const nonce = await web3.eth.getTransactionCount(address);
  const gasPrice = await web3.eth.getGasPrice();

  const transaction = {
    nonce,
    gasPrice,
    gas: 2000000,
    data: contractData
  };

  const signedTransaction = await account.signTransaction(transaction);

  const transactionReceipt = await web3.eth.sendSignedTransaction(signedTransaction.rawTransaction);
```

**Web3 version**: 1.1.0

**Command(s) triggering the issue**:
```
  const transactionReceipt = await web3.eth.sendSignedTransaction(signedTransaction.rawTransaction);
```

**API output**: 
```
Error: Given address "0x" is not a valid Aion address.
Failed to check for transaction receipt:
{}
``` 
I did some digging around within the codebase and found that the issue is originating from the following [line](
https://github.com/aionnetwork/aion_web3/blob/567e0f90fa7ac8cec581c3645c2dfd659c8013c2/packages/web3-core-helpers/src/formatters.js#L335) within the `web3-core-helpers/src/formatters.js` file.

```
  if (log.address) {
        log.address = utils.toChecksumAddress(log.address);
    }
```

Here is an example of  transaction receipt for a contract creation: 
```
{
  blockHash: '0xd6b9117e6673901489a448c73662dca2c320137f1df84d609c33eb9e09c00a0c',
  nrgPrice: '0x010000000000',
  logsBloom:
    '00000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000040000000000000000000000000000040000000000020000000000000000000040000000000000000000000000000000000000000000000000000040000100000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000010000000000000000008002000000000810000200000000000000000104800000000000010000000000200000000000000000000000000000000000040000000000000000000',
  nrgUsed: 921075,
  contractAddress: '0xa0513ec9240298c3ccf6f9e978f78911f7b8f0d0ff46ac5c35fe030835dcb2bb',
  transactionIndex: 0,
  transactionHash: '0x1f78e7fb5fc0da537df839c78041133d7419c910e55c5aa9af777af955ebb6f5',
  gasLimit: '0x1e8480',
  cumulativeNrgUsed: 921075,
  gasUsed: '0x0e0df3',
  blockNumber: 1047393,
  root: '1b35f2d7e01ec82567a6b7fdef0571f9beff0e36c275cee97d2b24960c9db100',
  cumulativeGasUsed: '0xe0df3',
  from: '0xa0fff1cee712cd2d6e59621b93ffa7d07dee3a0dc47cda92106098ae421bc849',
  to: '0x',
  logs: [
    {
      address: '0x',
      logIndex: 0,
      data: '0x',
      topics: [
        '0x7f0c55adb7f69e3decf3ca20f9a2367b205d728e6905eea6c4fb6f3934f842cc',
        '0x0000000000000000000000000000000000000000000000000000000000009c40',
        '0xa0fff1cee712cd2d6e59621b93ffa7d07dee3a0dc47cda92106098ae421bc849'
      ],
      blockNumber: 1047393,
      transactionIndex: 0
    },
    {
      address: '0x',
      logIndex: 1,
      data: '0x',
      topics: [
        '0x9096ccaf3bc136981b8a043d4e5ef1396a340697147a05ff0597f635003acc00',
        '0xa0513ec9240298c3ccf6f9e978f78911f7b8f0d0ff46ac5c35fe030835dcb2bb',
        '0x87c6410c4c8253a24871535e38b61ccf76bfc709cbfb34b3a5a65be94a2d84a6',
        '0xa0513ec9240298c3ccf6f9e978f78911f7b8f0d0ff46ac5c35fe030835dcb2bb'
      ],
      blockNumber: 1047393,
      transactionIndex: 0
    }
  ],
  gasPrice: '0x010000000000',
  status: '0x1'
}
```

The `logs` Object yields an array with 2 objects which have an address of '0x' as shown above. Which then causes the `utils.toChecksumAddress` [method](https://github.com/aionnetwork/aion_web3/blob/567e0f90fa7ac8cec581c3645c2dfd659c8013c2/packages/web3-utils/src/index.js#L270) to throw the error shown above. 

**Possible Solution:** Check if the `receipt` object has a contract address (thus implying a contract deployment) when formatting the logs object. Then format the log object accordingly. But more importantly, I'm not sure why `logs` is returning objects with an `address` field of `0x`.

**Comment by aion-kelvin** [comment]
Hey,

In your code snippet, I noticed that the `transaction` object does not have a `from` field.  Can you try adding that and see if it works?  The value should the address of the account you want to use to deploy the contract.  Looking at the rest of your code, if `account` is your account, then `account.address` will contain the address you need.

**Comment by hamzahayat** [comment]
Hey @aion-kelvin, 

I have tried adding the `from` field within the transaction object as well. However, that did not help with the situation. 

I believe the issue lies within the generation of the logs object when the `transactionReceipt` will gets generated.

**Comment by hamzahayat** [comment]
I've forked the library, meddled around with the source code and written a quick fix for anyone that's interested. It's by no means a proper fix. Simply a band-aid.  
The link to the changes that I've made are [here.](https://github.com/hamzahayat/aion_web3/commit/413366a06f2fb31f29ad79fa09ad2c3c21d214be)

**Comment by ToJen** [comment]
Would the patch work for contract function interaction too? cc: @arjitkhullar

**Comment by hamzahayat** [comment]
@aion-kelvin I'm not sure what's changed. But looks like the logs array isn't returning an address of `0x` anymore. Therefore it isn't failing the formatting checks, and the transaction receipt is being returned correctly. 

I didn't change anything within my codebase, nor within `aion-web3` lol. It could have been something on nodesmiths side? I'm not sure. 

Regardless, I'll close the thread. 

@ToJen You do not need to use the patch that I wrote. You should be able to deploy a ERC-777 compliant contract, as well as transfer those tokens. You can checkout my example code for reference [here](https://github.com/hamzahayat/deploy-aion-token).

**Comment by ToJen** [comment]
They may have made some fixes recently @hamzahayat
