### ISSUE TITLE
Remove non-supported web3 functions

### ISSUE THREAD

**Issue by ali-sharif** [aionnetwork/aion_web3#8]
Ex. 
web3.eth.getUncle

**Comment by erik-iglikov** [comment]
@ali-sharif Is this still an issue?

**Comment by ali-sharif** [comment]
This was an open issue for the old web3 client. Probably not an issue for the 1.x.x version.

On the kernel side, all deviations from the JSON RPC spec are documented here: https://github.com/aionnetwork/aion/wiki/JSON-RPC-API-Docs

**Comment by erik-iglikov** [comment]
@ali-sharif ok, I see.
@aion-kelvin can you take a look at it when you get a chance to make sure that's fixed in 1.x.x version?

**Comment by aion-kelvin** [comment]
We did remove some clearly non-supported stuff from v1.x.x after we merged in eth-web3's v1, but there's probably some that we missed.  I'll take a look and fix if I find any.
